export const regionsList = {
    europa: [
      { nombre: 'Alemania', isocode: 'DE' },
      { nombre: 'Francia', isocode: 'FR' },
      { nombre: 'Albania', isocode: 'AL' },
      { nombre: 'Austria', isocode: 'AT' },
      { nombre: 'Bélgica', isocode: 'BE' },
      { nombre: 'Bulgaria', isocode: 'BG' },
      { nombre: 'Suiza', isocode: 'CH' },
      { nombre: 'Chipre', isocode: 'CY' },
      { nombre: 'República Checa', isocode: 'CZ' },
      { nombre: 'Dinamarca', isocode: 'DK' },
      { nombre: 'Estonia', isocode: 'EE' },
      { nombre: 'España', isocode: 'ES' },
      { nombre: 'Finlandia', isocode: 'FI' },
      { nombre: 'Reino Unido', isocode: 'GB' },
      { nombre: 'Guernsey', isocode: 'GG' },
      { nombre: 'Grecia', isocode: 'GR' },
      { nombre: 'Croacia', isocode: 'HR' },
      { nombre: 'Hungría', isocode: 'HU' },
      { nombre: 'Irlanda', isocode: 'IE' },
      { nombre: 'Israel', isocode: 'IL' },
      { nombre: 'Isla de Man', isocode: 'IM' },
      { nombre: 'Islandia', isocode: 'IS' },
      { nombre: 'Italia', isocode: 'IT' },
      { nombre: 'Jersey', isocode: 'JE' },
      { nombre: 'Liechtenstein', isocode: 'LI' },
      { nombre: 'Lituania', isocode: 'LT' },
      { nombre: 'Luxemburgo', isocode: 'LU' },
      { nombre: 'Letonia', isocode: 'LV' },
      { nombre: 'Moldavia', isocode: 'MD' },
      { nombre: 'Malta', isocode: 'MT' },
      { nombre: 'Países Bajos', isocode: 'NL' },
      { nombre: 'Noruega', isocode: 'NO' },
      { nombre: 'Polonia', isocode: 'PL' },
      { nombre: 'Portugal', isocode: 'PT' },
      { nombre: 'Rumanía', isocode: 'RO' },
      { nombre: 'Suecia', isocode: 'SE' },
      { nombre: 'Eslovenia', isocode: 'SI' },
      { nombre: 'Eslovaquia', isocode: 'SK' },
      { nombre: 'San Marino', isocode: 'SM' },
      { nombre: 'Turquía', isocode: 'TR' },
      { nombre: 'Ucrania', isocode: 'UA' },
      { nombre: 'Uzbekistán', isocode: 'UZ' },
      { nombre: 'Ciudad del Vaticano', isocode: 'VA' }
    ],
    africa: [
      { nombre: 'Suazilandia', isocode: 'SZ' },
        { nombre: 'Madagascar', isocode: 'MG' },
        { nombre: 'Malawi', isocode: 'MW' },
        { nombre: 'Burkina Faso', isocode: 'BF' },
        { nombre: 'Botsuana', isocode: 'BW' },
        { nombre: 'Republica Centroafricana', isocode: 'CF' },
        { nombre: 'Chad', isocode: 'TD' },
        { nombre: 'Congo', isocode: 'CG' },
        { nombre: 'Republica Democratica del Congo', isocode: 'CD' },
        { nombre: 'Costa de Marfil', isocode: 'CI' },
        { nombre: 'Egipto', isocode: 'EG' },
        { nombre: 'Gabon', isocode: 'GA' },
        { nombre: 'Reunion', isocode: 'RE' },
        { nombre: 'Guinea-Bisau', isocode: 'GW' },
        { nombre: 'Kenia', isocode: 'KE' },
        { nombre: 'Liberia', isocode: 'LR' },
        { nombre: 'Mali', isocode: 'ML' },
        { nombre: 'Marruecos', isocode: 'MA' },
        { nombre: 'Niger', isocode: 'NE' },
        { nombre: 'Nigeria', isocode: 'NG' },
        { nombre: 'Senegal', isocode: 'SN' },
        { nombre: 'Seychelles', isocode: 'SC' },
        { nombre: 'Sudafrica', isocode: 'ZA' },
        { nombre: 'Sudan', isocode: 'SD' },
        { nombre: 'Tanzania', isocode: 'TZ' },
        { nombre: 'Tunez', isocode: 'TN' },
        { nombre: 'Uganda', isocode: 'UG' },
        { nombre: 'Zambia', isocode: 'ZM' }
      ],
      asia: [
        { nombre: 'Hong Kong', isocode: 'HK' },
        { nombre: 'Singapur', isocode: 'SG' },
        { nombre: 'Malasia', isocode: 'MY' },
        { nombre: 'Indonesia', isocode: 'ID' },
        { nombre: 'Tailandia', isocode: 'TH' },
        { nombre: 'Macao', isocode: 'MO' },
        { nombre: 'Korea', isocode: 'KR' },
        { nombre: 'Taiwan', isocode: 'TW' },
        { nombre: 'China', isocode: 'CN' },
        { nombre: 'Vietnam', isocode: 'VN' }
      ],
      sudesteAsiatico : [
        { nombre: 'Singapur', isocode: 'SG' },
        { nombre: 'Malasia', isocode: 'MY' },
        { nombre: 'Tailandia', isocode: 'TH' },
        { nombre: 'Indonesia', isocode: 'ID' },
        { nombre: 'Vietnam', isocode: 'VN' }
      ],
      norteamerica : [
        {nombre: 'Estados Unidos', isocode: 'US'},
        {nombre: 'Canada', isocode: 'CA'},
        {nombre: 'Mexico', isocode: 'MX'}
      ]
  };