import { Discount } from "../Types/TDiscount"

export const discountCodes : Discount[] = [{
    code: 'VIVIRVIAJANDO',
    acceptedVariations: [
        'VIVIRVIAJANDO',
        'vivirviajando',
        'Vivirviajando',
        'Vivir viajando',
        'vivir viajando',
        'VivirViajando',
        'Vivir Viajando'
    ],
    discountPercentage: 15
},
{
    code: 'ViajareSIM5',
    acceptedVariations: [
        'viajaresim5',
        'viajar esim 5',
        'Viajar esim 5',
        'Viajar eSIM 5',
        'viajarEsim5',
        'ViajareSIM5',
        'ViajareSim5',
        'viajareSIM5',
        'viajaresim 5',
        'viajar esim5',
        'VIAJARESIM5',
        'VIAJAR ESIM 5',
        'viajar-esim-5',
        'viajar_esim_5',
        'viajare sim5',
        'viajare-sim-5',
        'viajar e sim 5',
        'viajareSim5',
        'viajar e-sim 5',
        'viajar e sim5',
        'viajaresim-5',
        'viajaresim_5',
        'viajare-sim5',
        'viajare_sim5',
        'viajar sim 5',
        'viajarsim5',
        'viajar sim5'
    ],
    discountPercentage: 5
},
{
    code: 'ViajareSIM20',
    acceptedVariations: [
        'viajaresim20',
        'viajar esim 20',
        'Viajar esim 20',
        'Viajar eSIM 20',
        'viajarEsim20',
        'ViajareSIM20',
        'ViajareSim20',
        'viajareSIM20',
        'viajaresim 20',
        'viajar esim20',
        'VIAJARESIM20',
        'VIAJAR ESIM 20',
        'viajar-esim-20',
        'viajar_esim_20',
        'viajare sim20',
        'viajare-sim-20',
        'viajar e sim 20',
        'viajareSim20',
        'viajar e-sim 20',
        'viajar e sim20',
        'viajaresim-20',
        'viajaresim_20',
        'viajare-sim20',
        'viajare_sim20',
        'viajar sim 20',
        'viajarsim20',
        'viajar sim20'
    ],
    discountPercentage: 20
},
{
    code: 'ViajareSIM25',
    acceptedVariations: [
        'viajaresim25',
        'viajar esim 25',
        'Viajar esim 25',
        'Viajar eSIM 25',
        'viajarEsim25',
        'ViajareSIM25',
        'ViajareSim25',
        'viajareSIM25',
        'viajaresim 25',
        'viajar esim25',
        'VIAJARESIM25',
        'VIAJAR ESIM 25',
        'viajar-esim-25',
        'viajar_esim_25',
        'viajare sim25',
        'viajare-sim-25',
        'viajar e sim 25',
        'viajareSim25',
        'viajar e-sim 25',
        'viajar e sim25',
        'viajaresim-25',
        'viajaresim_25',
        'viajare-sim25',
        'viajare_sim25',
        'viajar sim 25',
        'viajarsim25',
        'viajar sim25'
    ],
    discountPercentage: 25
},
{
    code: 'ViajareSIM30',
    acceptedVariations: [
        'viajaresim30',
        'viajar esim 30',
        'Viajar esim 30',
        'Viajar eSIM 30',
        'viajarEsim30',
        'ViajareSIM30',
        'ViajareSim30',
        'viajareSIM30',
        'viajaresim 30',
        'viajar esim30',
        'VIAJARESIM30',
        'VIAJAR ESIM 30',
        'viajar-esim-30',
        'viajar_esim_30',
        'viajare sim30',
        'viajare-sim-30',
        'viajar e sim 30',
        'viajareSim30',
        'viajar e-sim 30',
        'viajar e sim30',
        'viajaresim-30',
        'viajaresim_30',
        'viajare-sim30',
        'viajare_sim30',
        'viajar sim 30',
        'viajarsim30',
        'viajar sim30'
    ],
    discountPercentage: 30
}
]