export const preguntasFrecuentes = [
  { category: 'recarga', question: "¿Puedo recargar mi eSIM?", answer: 'Si, puedes hacerlo ingresando al Holafly Center o a través de nuestra App.' },
  { category: 'soporte', question: "¿Qué puedo hacer si borro o pierdo el código QR de mi eSIM?" },
  { category: 'uso', question: "¿Debo activar el roaming de datos en mi móvil?" },
  { category: 'uso', question: "¿Cuál es la velocidad que voy a tener con la eSIM de ViajareSIM?" },
  { category: 'uso', question: "¿Cómo mantengo mi número en Whatsapp?" },
  { category: 'recarga', question: "¿Cuándo recibiré mi eSIM?" },
  { category: 'soporte', question: "¿Qué teléfonos inteligentes tienen soporte para eSIM?" },
  { category: 'uso', question: "¿Puedo llamar y enviar SMS con mi eSIM de ViajareSIM?" },
  { category: 'uso', question: "¿Cuándo empiezan a contar los días de mi plan de datos?" },
  { category: 'recarga', question: "¿Cómo puedo recibir un reembolso?" },
  { category: 'uso', question: "¿Puedo usar mi tarjeta SIM física a la vez que la eSIM?" },
  { category: 'soporte', question: "¿Cómo puedo borrar la eSIM después de agotar el plan de datos?" },
  { category: 'uso', question: "¿Cuántas veces puedo usar esta eSIM?" },
  { category: 'uso', question: "¿Cómo puedo comprobar cuántos datos me quedan?" },
  { category: 'instalacion', question: "¿Cuándo debo instalar mi eSIM?" },
  { category: 'instalacion', question: "¿Cómo configuro la eSIM en mi dispositivo?" },
  { category: 'uso', question: "¿Cuántos datos incluye mi eSIM?" },
  { category: 'uso', question: "¿Puedo compartir datos con otros dispositivos?" }
];