export const ciudades = [
    "los angeles",
    "miami",
    "nueva york",
    "orlando",
    "san francisco",
    "paris",
    "niza",
    "tokio",
    "cancun",
    "londres",
    "zurich",
    "lucerna"
];

export const RegionesCompletos = [
    "africa",
    "albania",
    "alemania",
    "america latina",
    "andorra",
    "antigua y barbuda",
    "arabia saudita",
    "argelia",
    "Argentina", 
    "armenia", 
    "aruba",
    "asia",
    "australia",
    "austria",
    "azerbaiyán",
    "bahamas",
    "bangladesh",
    "barbados",
    "belgica",
    "bermudas",
    "bolivia",
    "bosnia y herzegovina",
    "botsuana",
    "brasil",
    "brunei",
    "bulgaria",
    "burkina faso",
    "camboya",
    "camerun",
    "canada",
    "caribe",
    "catar",
    "chad",
    "chile",
    "china",
    "chipre",
    "colombia",
    "corea del sur",
    "costa de marfil",
    "costa rica",
    "croacia",
    "curacao",
    "dinamarca",
    "dominica",
    "ecuador",
    "eeuu",
    "egipto",
    "el mundo",
    "el salvador",
    "emiratos arabes",
    "eslovaquia",
    "eslovenia",
    "espana",
    "Estados Unidos",
    "estonia",
    "europa",
    "fiji",
    "filipinas",
    "finlandia",
    "francia",
    "gabon",
    "georgia",
    "ghana",
    "gibraltar",
    "granada",
    "grecia",
    "groenlandia",
    "guadalupe",
    "guam",
    "guatemala",
    "guayana francesa",
    "guernsey",
    "haiti",
    "hawaii",
    "honduras",
    "hong kong",
    "hungria",
    "india",
    "indonesia",
    "iran",
    "iraq",
    "irlanda",
    "isla de man",
    "islandia",
    "islas cayman",
    "islas feroe",
    "islas turcas y caicos",
    "islas virgenes britanicas",
    "israel",
    "italia",
    "jamaica",
    "japon",
    "jersey",
    "jordania",
    "kazajistan",
    "kenia",
    "kirguistan",
    "kuwait",
    "laos",
    "letonia",
    "liberia",
    "liechtenstein",
    "lituania",
    "luxemburgo",
    "macao",
    "macedonia del norte",
    "madagascar",
    "malasia",
    "malawi",
    "mali",
    "malta",
    "marruecos",
    "martinica",
    "mauricio",
    "mayotte",
    "medio oriente",
    "mexico",
    "moldavia",
    "monaco",
    "mongolia",
    "montenegro",
    "mozambique",
    "nepal",
    "nicaragua",
    "niger",
    "nigeria",
    "norteamerica",
    "noruega",
    "nueva zelanda",
    "oman",
    "paises bajos",
    "pakistan",
    "palestina",
    "panama",
    "papúa nueva guinea",
    "paraguay",
    "peru",
    "polonia",
    "portugal",
    "puerto rico",
    "reino unido",
    "republica centroafricana",
    "republica checa",
    "republica del congo",
    "republica democratica del congo",
    "republica dominicana",
    "reunion",
    "ruanda",
    "rumania",
    "rusia",
    "san bartolome (francia)",
    "san cristobal y nieves",
    "san martin (francia)",
    "santa lucia",
    "senegal",
    "serbia",
    "seychelles",
    "singapur",
    "sri lanka",
    "suazilandia",
    "sudafrica",
    "sudan",
    "suecia",
    "suiza",
    "suriname",
    "tailandia",
    "taiwan",
    "tanzania",
    "trinidad y tobago",
    "tunez",
    "turquia"
];